### ISSUE TITLE
Ticket 2: Develop Frontend View for Report Display

### ISSUE THREAD

**Issue by kmesiab** [kmesiab/orion#11]
# Develop Frontend View for Report Display

## Description
Create a view within the React frontend to display the analysis report. This view will show the results returned by the backend after processing the Git diff.

## Acceptance Criteria
- [x] Design and implement a report display component in React.
- [x] The component should handle and render report data neatly.
- [x] Seamlessly integrate this component into the overall UI.
- [x] #20

**Comment by frankie-mur** [comment]
Do we want a vertical two-column view?
Match each file (tab) with its returned report. WDYT?

**Comment by kmesiab** [comment]
Been on the fence.  I feel like the report gets squished. 

What if they were stacked with the report taking the top slot after it is returned?

**Comment by frankie-mur** [comment]
Hmm yeah I like that, I'll try a couple different things see what looks good

**Comment by frankie-mur** [comment]
PR #26 Merged
